/*Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

RESULT: CORRECT
*/

#include <stdio.h>

#define LIMIT 4000000

/*
I wanted to use recursion on this just for fun.
Returns the nth number of the Fibonacci sequence.
*/
unsigned long fib(int n) {
    if (n < 1) {
        return 1;
    }
    return fib(n-1) + fib(n-2)
}

int main() {

    unsigned long sum = 0;
    int i = 0;
    while (TRUE) {
        unsigned long current = fib(i);
        if (current > LIMIT) {
            break;
        }

        if (current % 2 == 0) {
            sum += current;
        }
        i++;
    }

    printf("SUM: %ld", sum);
    return 0;
}
